# Generated by Django 3.0.8 on 2020-12-31 20:32

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('droptag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='date_filed',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=datetime.date.today),
            preserve_default=False,
        ),
    ]
