# Generated by Django 3.0.8 on 2021-01-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('droptag', '0006_auto_20210109_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='note',
            new_name='about',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
