# Generated by Django 3.0.8 on 2021-01-10 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('droptag', '0007_auto_20210109_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
