# Generated by Django 3.0.8 on 2021-01-13 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('droptag', '0008_auto_20210110_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='geo_location',
        ),
    ]
