# Generated by Django 3.0.8 on 2021-01-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('droptag', '0009_remove_tag_geo_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='platform',
            field=models.CharField(choices=[('PSN', 'PlayStation'), ('XB', 'Xbox'), ('DC', 'Discord'), ('STM', 'Steam')], default='STM', max_length=32),
        ),
        migrations.AlterField(
            model_name='tag',
            name='time_met',
            field=models.DateField(),
        ),
    ]
