# Generated by Django 3.0.8 on 2021-01-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('droptag', '0012_auto_20210125_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id_link',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='discord_id',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='psn_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='steam_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='xbox_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
