# Generated by Django 3.0.8 on 2021-01-26 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('droptag', '0014_userprofile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='slug',
        ),
    ]
