# Generated by Django 3.0.8 on 2021-01-27 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('droptag', '0016_auto_20210127_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='user',
        ),
    ]
